import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "../../components/navigation/LeftSidebar";
import {NextIntlClientProvider, useMessages} from 'next-intl';
import MobileNav from "@/components/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: {locale} }) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages} locale={locale} >
        <body className={`${inter.className} bg-[#1d1d1d]`}>
          <MobileNav />
          <div className="flex flex-row">
            <LeftSidebar />
            <main className="border mt-7 mr-7 rounded-t-3xl bg-slate-100 xl:ml-[25%] ml-7 w-[100%]">
              {children}
            </main>
          </div>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
