import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "../../components/navigation/LeftSidebar";
import {NextIntlClientProvider, useMessages} from 'next-intl';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: {locale} }) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages} locale={locale} >
        <body className={`${inter.className} flex flex-row bg-[#1d1d1d]`}>
          <LeftSidebar />
          <main className="w-10/12 border mt-8 mr-8 rounded-t-3xl bg-slate-100">
            {children}
          </main>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
